# Azure Static Web Apps CI/CD Configuration
# Docs: https://learn.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-azure.outputs.azure_static_web_apps_api_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy
        id: deploy-to-azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                      # Root folder of your React app
          api_location: null
          output_location: "build"               # For Create React App use "build"; Vite uses "dist"
          app_build_command: "npm run build"
          app_artifact_location: "build"
          app_settings: |
            NODE_VERSION=20
